include:
  - project: 'adra-network/aws-core-deployment-roles'
    ref: main
    file: '/gitlab-templates/trunk-based-pipeline-frontend.yml'

variables:
  MULTIPLE_CLOUDFRONT_DISTRIBUTION: 'true'

cloudflare_deploy:
  image: node:latest
  stage: deploy
  script:
    - echo "Deploying to cloudflare pages"
    - npm i wrangler -g
    - CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN wrangler pages publish dist/ --project-name=$CLOUDFLARE_PROJECT_NAME --branch=$CI_COMMIT_BRANCH
