<template>
  <ToastUIViewer ref="toastuiViewer" class="adra-markdown-viewer" :initial-value="formattedValue" height="500px" />
</template>

<script setup>
import { defineProps } from 'vue'
import '@toast-ui/editor/dist/toastui-editor-viewer.css'

const props = defineProps({
  value: {
    type: String,
    default: "",
  }
})
const toastuiViewer = ref(null)
const formattedValue = ref(props.value)

watch(() => props.value, (_, __) => {
  formattedValue.value = toastuiViewer.value.invoke(
    'setMarkdown',
    props.value
  )
})

</script>

<style lang="css">
.adra-markdown-viewer .toastui-editor-contents {
  font-size: 1rem;
  color: black;
}

.adra-markdown-viewer .toastui-editor-contents p {
  margin: 0;
}

/* Settings position absolute to remove extra padding generated by libray */
.adra-markdown-viewer .toastui-editor-contents p:nth-child(2) {
  position: absolute;
}

.adra-markdown-viewer.small .toastui-editor-contents {
  font-size: 0.8rem;
  color: black;
}
</style>
